import fs from 'fs';
import path from 'path';
import simpleGit from 'simple-git';

const PROJECT_DIR = 'D:/STUDIA/READY PROJECT FOR WORK/GITHUB/aftident_product/aftident_product';

const COMMIT_MESSAGES = [
    "Updated the last modified date in the selected file to ensure the repository reflects the latest changes.",
    "Performed daily automated update to the last updated timestamp for tracking code modifications.",
    "Refreshed last updated comment in a source file to keep project documentation accurate and up to date.",
    "Chore: Added or updated the 'Last updated' timestamp comment to maintain consistency across files.",
    "Improved documentation by inserting a current modification date comment in one of the code files.",
    "Refactored the timestamp comment insertion to help with audit trails in the project repository.",
    "Fixed formatting of the 'Last updated' line to match project coding standards and conventions.",
    "Enhanced the automated commit script by updating file modification comments with today's date.",
    "Added metadata update: refreshed the 'Last updated' comment to assist with change tracking.",
    "Updated timestamp comments across the project as part of daily maintenance and version control hygiene.",
    "Fixed minor discrepancies in file comments to reflect accurate last update dates in the source code.",
    "Updated the modification date comment in the file to ensure synchronization with recent development work.",
    "Routine update of last modified timestamp to support automated commit and push operations.",
    "Added descriptive comments including the current date to keep documentation synchronized with code changes.",
    "Automated update: inserted or modified the 'Last updated' comment in the randomly selected source file.",
    "Enhanced version control records by updating file timestamp comments for better change traceability.",
    "Maintenance commit: synchronized last update comments with actual modification dates for clarity.",
    "Improved commit messages by adding context about timestamp updates to the relevant source files.",
    "Refined automated update process with accurate and consistent 'Last updated' timestamps across files.",
    "Daily update: committed changes including refreshed modification date comments to track progress.",
    "Updated import paths in several files to ensure module resolution correctness.",
    "Fixed issue with asynchronous loading in 'DataFetcher.js' to prevent race conditions.",
    "Improved error handling in 'ApiClient.js' by adding more descriptive error messages.",
    "Refactored 'UserProfile.jsx' to separate concerns and enhance readability.",
    "Added unit tests for 'utils/validation.js' to increase code coverage and reliability.",
    "Updated CSS styles in 'Button.module.css' to improve accessibility and contrast ratios.",
    "Improved responsiveness in 'Header.jsx' for better display on mobile devices.",
    "Optimized image loading in 'Gallery.jsx' by implementing lazy loading.",
    "Corrected typo in 'README.md' to improve documentation quality.",
    "Upgraded dependencies to latest stable versions to maintain security and compatibility.",
    "Refined build scripts in 'package.json' for faster and more efficient builds.",
    "Fixed merge conflicts from recent pull requests affecting 'App.jsx'.",
    "Improved logging in 'server.js' to help with debugging production issues.",
    "Enhanced input validation in 'Form.jsx' to prevent invalid user submissions.",
    "Removed deprecated API calls in 'NetworkService.js' and replaced with updated endpoints.",
    "Refactored routing logic in 'Router.js' to better support nested routes.",
    "Improved accessibility by adding ARIA labels in various components.",
    "Fixed memory leak issues identified in 'DataStore.js' under heavy load.",
    "Updated environment configuration to support new staging server.",
    "Added comments and documentation to 'utils/helpers.js' for better maintainability.",
    "Improved performance of sorting algorithms in 'SortUtils.js'.",
    "Enhanced security by sanitizing user input in 'AuthService.js'.",
    "Updated localization files to include recent translations and fixes.",
    "Fixed bug causing incorrect state updates in 'useCounter.js' hook.",
    "Improved test coverage for 'LoginForm.jsx' and related authentication modules.",
    "Refined error boundaries in React components to catch unexpected crashes.",
    "Updated deployment scripts to automate release to production environment.",
    "Fixed styling issues in 'Footer.jsx' on smaller screen sizes.",
    "Improved code comments to clarify complex logic in 'ChartComponent.js'.",
    "Refactored 'Modal.jsx' to improve reusability and reduce code duplication.",
    "Optimized API request batching in 'ApiClient.js' to reduce server load.",
    "Updated user interface to align with latest design specifications.",
    "Fixed broken links in project documentation and wiki pages.",
    "Improved state management in 'useAuth.js' hook for better session handling.",
    "Enhanced caching strategies in 'DataFetcher.js' to improve load times.",
    "Refined error messages displayed to users during form submission.",
    "Added retry logic for network requests in 'NetworkService.js'.",
    "Updated third-party libraries to fix known security vulnerabilities.",
    "Fixed layout issues caused by flexbox properties in 'Navbar.jsx'.",
    "Improved unit test reliability by mocking asynchronous dependencies.",
    "Refactored 'NotificationService.js' to support multiple notification types.",
    "Updated ESLint configuration to enforce stricter coding standards.",
    "Added pre-commit hooks to run linting and tests automatically.",
    "Improved build performance by caching dependencies in CI pipeline.",
    "Fixed issues with dark mode support in several UI components.",
    "Enhanced file upload component to support multiple file selection.",
    "Refined database query logic in 'DataAccessLayer.js' for faster response times.",
    "Updated analytics tracking code to support new event types.",
    "Fixed issue with date parsing in 'DateUtils.js' across different time zones.",
    "Improved UX by adding loading spinners during data fetch operations.",
    "Refactored 'SearchBar.jsx' for better debouncing and input handling.",
    "Added support for internationalization (i18n) in key components.",
    "Improved accessibility by ensuring keyboard navigation works across app.",
    "Fixed issues with session timeout handling in authentication flow.",
    "Enhanced error reporting by integrating with external monitoring services.",
    "Refined CSS modules to avoid naming conflicts and improve maintainability.",
    "Updated README with setup instructions and troubleshooting tips.",
    "Fixed bugs related to pagination in data tables.",
    "Improved code modularity by splitting large components into smaller ones.",
    "Added feature flag support to toggle new features in production.",
    "Refactored state selectors for better memoization and performance.",
    "Updated Docker configuration files for smoother container builds.",
    "Improved user feedback with success and error toast notifications.",
    "Fixed issues with form validation on mobile devices.",
    "Enhanced security by implementing rate limiting on API endpoints.",
    "Updated service worker to improve offline support and caching.",
    "Refactored 'Header.jsx' to use hooks instead of class components.",
    "Added analytics event tracking for user interactions on landing page.",
    "Improved localization fallback mechanisms for missing translations.",
    "Fixed issues with CSS grid layouts on legacy browsers.",
    "Updated dependencies to address vulnerabilities reported by audit tools.",
    "Improved accessibility by adding alt text to all images.",
    "Refined logic in 'AuthProvider.jsx' for more reliable token refresh.",
    "Added utility functions for date formatting and parsing.",
    "Fixed crash caused by null reference errors in 'Dashboard.jsx'.",
    "Improved logging format for easier debugging in production.",
    "Enhanced user profile page with additional customization options.",
    "Refactored 'Sidebar.jsx' to improve responsiveness and usability.",
    "Updated API client to support new endpoints and data formats.",
    "Improved error handling in async actions using Redux Thunk.",
    "Fixed memory issues in long-running background tasks.",
    "Added integration tests for critical user flows.",
    "Improved SEO by updating meta tags and page titles dynamically.",
    "Refactored 'Footer.jsx' to use CSS variables for easier theming.",
    "Fixed alignment issues in form elements across different browsers.",
    "Enhanced documentation with architecture diagrams and flowcharts.",
    "Updated code to comply with latest ECMAScript standards.",
    "Improved loading performance by optimizing bundle size.",
    "Added support for dark mode toggle in settings page.",
    "Refined state management to avoid unnecessary re-renders.",
    "Fixed bugs in drag-and-drop functionality in file uploader.",
    "Improved form input validation with regex patterns.",
    "Updated third-party SDK versions to latest releases.",
    "Added animation effects for UI transitions.",
    "Fixed issues with date pickers on mobile devices.",
    "Enhanced notification system to queue messages properly.",
    "Refactored codebase to use TypeScript for better type safety.",
    "Improved accessibility by ensuring color contrast meets standards.",
    "Updated unit tests to cover edge cases more thoroughly.",
    "Fixed security issues related to cross-site scripting (XSS).",
    "Added feature to export data in CSV format.",
    "Improved UI responsiveness on tablets and smaller devices.",
    "Refactored 'LoginForm.jsx' to simplify authentication logic.",
    "Fixed issues with cookie handling in authentication flow.",
    "Improved error messages displayed in modal dialogs.",
    "Added support for multiple languages in user interface.",
    "Refined code formatting with Prettier for consistent style.",
    "Updated build process to include source maps for debugging.",
    "Fixed intermittent failures in CI test runs.",
    "Improved documentation on API usage and endpoints.",
    "Added client-side caching for improved load times.",
    "Refactored 'useFetch' hook for better error handling.",
    "Updated styling to match new brand guidelines.",
    "Fixed accessibility issues with focus management.",
    "Improved backend API response times by optimizing queries.",
    "Added automated performance tests using Lighthouse.",
    "Refactored 'Modal.jsx' to better support dynamic content.",
    "Improved code comments to clarify complex business logic.",
    "Fixed bugs related to user role permissions.",
    "Added integration with third-party authentication providers.",
    "Improved UX flow for password reset feature.",
    "Refactored 'NotificationService.js' to queue notifications efficiently.",
    "Fixed layout problems caused by flexbox inconsistencies.",
    "Added logging for critical application events.",
    "Improved error recovery after failed API requests.",
    "Updated dependencies to remove deprecated packages.",
    "Enhanced security by validating JWT tokens more strictly.",
    "Fixed UI glitches on high-DPI screens.",
    "Added loading indicators for long-running operations.",
    "Refactored 'DataTable.jsx' to improve sorting and filtering.",
    "Improved test reliability by mocking network requests.",
    "Updated README with contribution guidelines.",
    "Fixed bugs in offline mode synchronization.",
    "Added feature to import data from CSV files.",
    "Improved localization support with context-aware translations.",
    "Refined CSS animations for smoother user experience.",
    "Fixed issue with stale data in Redux store.",
    "Added preloading of critical assets for faster page loads.",
    "Improved error boundary handling for React components.",
    "Refactored code to reduce bundle size and improve loading speed.",
    "Updated API error handling to provide user-friendly messages.",
    "Fixed scrolling issues on mobile devices.",
    "Added unit tests for utility functions.",
    "Improved accessibility for screen readers.",
    "Refined input validation to prevent SQL injection.",
    "Updated Dockerfiles for better multi-stage builds.",
    "Added support for WebSocket connections.",
    "Improved UI for date range picker component.",
    "Fixed layout breakage in IE11.",
    "Enhanced logging to include user session details.",
    "Refactored 'AuthContext' to use React Context API effectively.",
    "Updated service configurations for better scalability.",
    "Added feature toggles for beta testing new features.",
    "Improved form error display messages.",
    "Fixed bugs causing memory leaks in React components.",
    "Added support for OAuth2 authentication flows.",
    "Improved build scripts to minimize output size.",
    "Refactored 'Sidebar.jsx' to improve accessibility features.",
    "Updated ESLint rules to catch potential bugs earlier.",
    "Added client-side form validation for better user experience.",
    "Improved error logging to external monitoring services.",
    "Fixed bugs related to asynchronous data fetching.",
    "Enhanced user onboarding experience with guided tours.",
    "Updated UI components to use design tokens.",
    "Refactored 'DataFetcher.js' to improve caching logic.",
    "Fixed security vulnerabilities reported by code audit.",
    "Improved deployment automation using CI/CD pipelines.",
    "Added support for Google Analytics event tracking.",
    "Refined localization files for consistency across languages.",
    "Fixed regression bugs introduced in previous release.",
    "Improved accessibility of modal dialogs with focus trapping.",
    "Updated code comments to follow JSDoc standards.",
    "Added support for custom themes in UI components.",
    "Fixed issues with infinite scrolling implementation.",
    "Improved input masking for phone numbers and dates.",
    "Refactored 'AuthService.js' for better token management.",
    "Updated dependencies to improve application stability.",
    "Fixed layout shifts causing visual glitches during page load.",
    "Improved error feedback during file uploads.",
    "Added integration tests for API endpoints.",
    "Refined CSS to improve print stylesheet formatting.",
    "Updated README to include new project setup steps.",
    "Fixed bugs related to browser compatibility.",
    "Improved keyboard navigation across interactive components.",
    "Added feature to export reports in PDF format.",
    "Refactored codebase to reduce technical debt.",
    "Improved error handling in promise chains.",
    "Fixed issues with session storage synchronization.",
    "Added support for international phone number formatting.",
    "Improved styling of form elements for better UX.",
    "Updated dependencies to remove security warnings.",
    "Refined state management using Redux Toolkit.",
    "Fixed memory leaks in background workers.",
    "Added logging for API request durations.",
    "Improved accessibility of dropdown menus.",
    "Refactored 'Modal.jsx' to support multiple instances.",
    "Updated unit tests to mock API responses more effectively.",
    "Fixed bugs related to user notifications.",
    "Improved input validation to prevent XSS attacks.",
    "Added support for dark mode in mobile app.",
    "Refined error messages for better user understanding.",
    "Updated build configuration for faster incremental builds.",
    "Fixed bugs in pagination controls.",
    "Improved UX by adding confirmation dialogs for destructive actions.",
    "Added support for multi-factor authentication.",
    "Refactored API client to handle rate limiting gracefully.",
    "Updated localization strings with improved phrasing.",
    "Fixed layout issues in grid components.",
    "Improved performance by memoizing expensive computations.",
    "Added support for real-time data updates via WebSockets.",
    "Refined code comments to improve maintainability.",
    "Updated dependencies to latest stable releases.",
    "Fixed bugs causing crashes on certain devices.",
    "Improved test coverage for critical application modules.",
    "Added analytics tracking for new user registration flow.",
    "Refactored 'useForm' hook for better state management.",
    "Updated UI to comply with accessibility guidelines.",
    "Fixed issues with form submission on slow networks.",
    "Improved loading indicators for better user feedback.",
    "Added automated linting to CI pipeline.",
    "Refined database schema to support new features.",
    "Updated deployment scripts to support rollback functionality.",
    "Fixed bugs in data export functionality.",
    "Improved error handling in background jobs.",
    "Added support for push notifications.",
    "Refactored authentication flow to improve security.",
    "Updated dependencies to patch critical vulnerabilities.",
    "Fixed layout bugs in responsive navigation menus.",
    "Improved code readability by renaming variables.",
    "Added tests for edge case scenarios.",
    "Refined API response caching strategies.",
    "Updated documentation with API usage examples.",
    "Fixed issues with drag-and-drop in file manager.",
    "Improved accessibility of tab navigation.",
    "Added support for custom user roles and permissions.",
    "Refactored state management to use React Query.",
    "Updated build scripts to automate version bumping.",
    "Fixed bugs causing incorrect data rendering.",
    "Improved error messages during payment processing.",
    "Added feature to export user data as JSON.",
    "Refined UI animations for smoother transitions.",
    "Updated dependencies to reduce bundle size.",
    "Fixed bugs related to timezone conversions.",
    "Improved test reliability with snapshot testing.",
    "Added support for SSO (Single Sign-On) authentication.",
    "Refactored 'Dashboard.jsx' to improve performance.",
    "Updated localization files for newly added features.",
    "Fixed layout issues with flexbox alignment.",
    "Improved error logging for uncaught exceptions.",
    "Added caching for frequently requested data.",
    "Refined input validation rules for forms.",
    "Updated README to include troubleshooting tips.",
    "Fixed bugs causing infinite loops in event handlers.",
    "Improved accessibility of form labels.",
    "Added support for file drag-and-drop uploads.",
    "Refactored codebase to adopt functional components.",
    "Updated third-party libraries for security patches.",
    "Fixed UI bugs on iOS devices.",
    "Improved error handling during API rate limits.",
    "Added support for exporting charts as images.",
    "Refined database indexing to improve query performance.",
    "Updated dependencies to address audit warnings.",
    "Fixed bugs related to user session expiration.",
    "Improved documentation for deployment procedures.",
    "Added feature flag management for beta releases.",
    "Refactored Redux actions and reducers for clarity.",
    "Updated build tools to latest versions.",
    "Fixed styling inconsistencies across browsers.",
    "Improved accessibility by adding skip navigation links.",
    "Added integration with external payment gateways.",
    "Refined form input handling to prevent double submissions.",
    "Updated localization to support right-to-left languages.",
    "Fixed bugs in multi-step form navigation.",
    "Improved test coverage with additional integration tests.",
    "Added automated deployment scripts for staging environment.",
    "Refactored code to support micro-frontend architecture.",
    "Updated UI components to use CSS-in-JS solutions.",
    "Fixed bugs causing slow page loads.",
    "Improved error messages for invalid user input.",
    "Added support for browser notifications.",
    "Refined API authentication to improve security.",
    "Updated README with code style guidelines.",
    "Fixed bugs related to accessibility in modals.",
    "Improved performance by lazy loading non-critical assets.",
    "Added unit tests for new utility functions.",
    "Refactored form validation logic for reusability.",
    "Updated dependencies to fix compatibility issues.",
    "Fixed layout issues in grid-based dashboards.",
    "Improved error handling in Redux sagas.",
    "Added support for exporting reports in Excel format.",
    "Refined UI for better usability and aesthetics.",
    "Updated deployment configurations for cloud providers.",
    "Fixed bugs causing crashes during file uploads.",
    "Improved documentation with API versioning info.",
    "Added support for offline mode in web app.",
    "Refactored authentication middleware for better scalability.",
    "Updated ESLint configuration to support new rules.",
    "Fixed bugs in notification delivery system.",
    "Improved accessibility by adding ARIA roles.",
    "Added feature to customize user dashboard layout.",
    "Refined caching strategies for API responses.",
    "Updated third-party SDKs to latest stable versions.",
    "Fixed bugs related to browser compatibility in forms.",
    "Improved error feedback in user profile update forms.",
    "Added tests for error boundary components.",
    "Refactored state management to reduce boilerplate.",
    "Updated documentation to reflect recent API changes.",
    "Fixed bugs causing incorrect data sorting.",
    "Improved UI responsiveness on various screen sizes.",
    "Added support for multi-language content management.",
    "Refined CSS styles to improve theme switching.",
    "Updated build process to include automatic changelog generation.",
    "Fixed bugs with asynchronous action creators.",
    "Improved error reporting with Sentry integration.",
    "Added feature to export logs for debugging.",
    "Refactored 'useAuth' hook to support token refresh.",
    "Updated localization files with new language support.",
    "Fixed layout issues in mobile navigation menus.",
    "Improved accessibility by enhancing keyboard focus indicators.",
    "Added support for user avatar uploads.",
    "Refined API error handling to retry transient failures.",
    "Updated dependencies to remove deprecated packages.",
    "Fixed bugs causing incorrect rendering in chart components.",
    "Improved logging for debugging intermittent issues.",
    "Added support for multiple user roles in permissions system.",
    "Refactored UI components for better reusability.",
    "Updated README with common troubleshooting steps.",
    "Fixed bugs related to form input sanitization.",
    "Improved state management using Redux Toolkit slices.",
    "Added integration with third-party analytics platforms.",
    "Refined CSS to fix cross-browser inconsistencies.",
    "Updated build scripts to improve continuous integration.",
    "Fixed issues with drag-and-drop file uploads.",
    "Improved error messages to be more user-friendly.",
    "Added unit tests for Redux reducers.",
    "Refactored codebase to adopt hooks and functional components.",
    "Updated dependencies to improve security posture.",
    "Fixed layout glitches on tablet devices.",
    "Improved accessibility by labeling form inputs correctly.",
    "Added feature toggle to enable or disable experimental UI.",
    "Refined API response validation to catch malformed data.",
    "Updated deployment scripts to enable zero-downtime deployments.",
    "Fixed bugs related to infinite scroll behavior.",
    "Improved user feedback during slow network conditions.",
    "Added support for dark mode in all UI components.",
    "Refactored state selectors to optimize performance.",
    "Updated documentation with architecture decision records.",
    "Fixed issues with third-party library integrations.",
    "Improved error boundary handling to prevent app crashes.",
    "Added support for custom CSS variables in themes.",
    "Refined input debouncing for improved search performance.",
    "Updated build configuration to enable tree shaking.",
    "Fixed bugs in form step validation logic.",
    "Improved user onboarding by adding tooltips.",
    "Added integration tests for critical user flows.",
    "Refactored code to use TypeScript for better type safety.",
    "Updated dependencies to fix performance bottlenecks.",
    "Fixed bugs causing race conditions in async operations.",
    "Improved styling consistency across different browsers.",
    "Added support for custom email templates.",
    "Refined error logging to capture more context.",
    "Updated UI to improve responsiveness on mobile devices.",
    "Fixed bugs related to file permission errors.",
    "Improved error handling for network timeouts.",
    "Added feature to track user activity for analytics.",
    "Refactored API error responses to standardize format.",
    "Updated README with new setup scripts.",
    "Fixed layout issues with sticky headers.",
    "Improved accessibility for screen reader users.",
    "Added support for internationalization (i18n) in all components.",
    "Refined caching layers to reduce API calls.",
    "Updated build tools to support modern JavaScript features.",
    "Fixed bugs causing data loss in form submissions.",
    "Improved user experience with better loading skeletons.",
    "Added support for exporting user activity logs.",
    "Refactored 'SettingsPage.jsx' to modularize code.",
    "Updated localization files for new dialects.",
    "Fixed UI bugs in dark mode.",
    "Improved error handling for third-party API failures.",
    "Added tests to cover edge cases in form validation.",
    "Refined CSS variables for consistent theming.",
    "Updated build configuration to speed up incremental builds.",
    "Fixed bugs with keyboard shortcuts.",
    "Improved accessibility by adding semantic HTML elements.",
    "Added support for exporting data in CSV format.",
    "Refactored form components for better reusability.",
    "Updated README with instructions for contributing.",
    "Fixed bugs related to user permission checks.",
    "Improved performance of list rendering with virtualization.",
    "Added feature to send automated email notifications.",
    "Refined error messages to be clearer and more actionable.",
    "Updated dependencies to support new browser versions.",
    "Fixed bugs in multi-user collaboration features.",
    "Improved accessibility of interactive charts.",
    "Added support for custom branding in client portals.",
    "Refactored API endpoints to follow RESTful conventions.",
    "Updated documentation to include API deprecation schedules.",
    "Fixed bugs causing intermittent failures in CI pipeline.",
    "Improved error feedback on login failures.",
    "Added feature to reset passwords via email link.",
    "Refined CSS styles to improve animation performance.",
    "Updated build scripts to optimize caching.",
    "Fixed layout bugs in profile pages.",
    "Improved accessibility by adding role attributes to buttons.",
    "Added support for custom keyboard shortcuts.",
    "Refactored authentication components to improve reusability.",
    "Updated dependencies to remove unused packages.",
    "Fixed bugs related to date formatting in reports.",
    "Improved error reporting in API middleware.",
    "Added support for webhooks in notification system.",
    "Refined form input masks for better user input control.",
    "Updated README with environment variable configuration details.",
    "Fixed bugs causing crashes in offline mode.",
    "Improved user feedback during image uploads.",
    "Added support for localization fallback mechanisms.",
    "Refactored Redux store structure for better scalability.",
    "Updated UI components to enhance visual consistency.",
    "Fixed bugs with media query breakpoints.",
    "Improved error handling in async API calls.",
    "Added feature to archive inactive user accounts.",
    "Refined testing strategy to include end-to-end tests.",
    "Updated dependencies to fix critical bugs.",
    "Fixed bugs in notification badge counts.",
    "Improved accessibility by enabling focus management in modals.",
    "Added support for two-factor authentication (2FA).",
    "Refactored code to improve modularity and separation of concerns.",
    "Updated documentation to include best practices for API usage.",
    "Fixed bugs causing layout breaks on small screens.",
    "Improved error messages for validation failures.",
    "Added feature to support user profile picture uploads.",
    "Refined caching and memoization techniques.",
    "Updated build tools to use Webpack 5.",
    "Fixed bugs related to search functionality.",
    "Improved accessibility of forms with aria-describedby.",
    "Added support for role-based access control (RBAC).",
    "Refactored API integration to use Axios interceptors.",
    "Updated localization files to fix typos.",
    "Fixed bugs causing performance degradation in rendering lists.",
    "Improved error handling in background synchronization.",
    "Added feature to export data in XML format.",
    "Refined UI components for mobile-first design.",
    "Updated README with contribution guidelines.",
    "Fixed bugs with video playback on certain browsers.",
    "Improved accessibility by ensuring all interactive elements are keyboard navigable.",
    "Added support for user activity heatmaps.",
    "Refactored Redux middleware to improve logging.",
    "Updated dependencies to the latest minor versions.",
    "Fixed bugs related to form reset behavior.",
    "Improved error messages for server-side validation.",
    "Added feature to import user data from CSV files.",
    "Refined CSS grid layouts for better responsiveness.",
    "Updated build configuration to support ES modules.",
    "Fixed bugs in client-side routing.",
    "Improved accessibility by adding landmarks for better screen reader navigation.",
    "Added support for custom notification sounds.",
    "Refactored code to use React.lazy and Suspense for code splitting.",
    "Updated localization files with context-aware translations.",
    "Fixed bugs causing incorrect user permission assignments.",
    "Improved performance of data synchronization.",
    "Added support for bulk user actions in admin panel.",
    "Refined API documentation with Swagger annotations.",
    "Updated README with common environment setup issues.",
    "Fixed bugs in sorting algorithm implementations.",
    "Improved accessibility of modal dialogs by managing focus and keyboard events.",
    "Added support for exporting user settings.",
    "Refactored form state management to use React Hook Form.",
    "Updated build tools to enable better tree shaking.",
    "Fixed bugs with CSS specificity issues.",
    "Improved error handling for failed image uploads.",
    "Added feature to schedule automated tasks.",
    "Refined UI feedback for form validation errors.",
    "Updated dependencies to fix memory leaks.",
    "Fixed bugs causing race conditions in state updates.",
    "Improved accessibility by adding aria-live regions.",
    "Added support for real-time collaboration features.",
    "Refactored 'ProfilePage.jsx' to improve code readability.",
    "Updated localization files for new regions.",
    "Fixed layout issues in responsive tables.",
    "Improved error handling in service worker caching.",
    "Added support for importing data from external APIs.",
    "Refined caching logic in React Query hooks.",
    "Updated README with performance tuning tips.",
    "Fixed bugs causing crashes during data synchronization.",
    "Improved user feedback during password reset flows.",
    "Added feature to support offline form submissions.",
    "Refactored authentication flows to improve user experience.",
    "Updated dependencies to fix security vulnerabilities.",
    "Fixed bugs causing incorrect form input behavior.",
    "Improved accessibility of tooltips and popovers.",
    "Added support for exporting data analytics dashboards.",
    "Refined UI components for improved accessibility.",
    "Updated build scripts to improve deployment speed.",
    "Fixed bugs in multi-language routing.",
    "Improved error messages for authentication errors.",
    "Added feature to customize notification preferences.",
    "Refactored API request handlers for better error reporting.",
    "Updated localization files to include new terminology.",
    "Fixed bugs causing inconsistent date display formats.",
    "Improved keyboard navigation in complex forms.",
    "Added support for user-generated content moderation.",
    "Refined CSS animations for better performance on mobile devices.",
    "Updated README with detailed changelog.",
    "Fixed bugs related to file upload progress indicators.",
    "Improved accessibility of color contrast ratios.",
    "Added feature to enable users to export their account data.",
    "Refactored 'SettingsPage.jsx' to simplify state logic.",
    "Updated localization files to improve translation accuracy.",
    "Fixed bugs causing layout breaks in IE11.",
    "Improved error handling for payment gateway timeouts.",
    "Added support for voice input in search functionality.",
    "Refined codebase to adopt TypeScript gradually.",
    "Updated build process to improve source map generation.",
    "Fixed bugs in API pagination logic.",
    "Improved accessibility by adding descriptive alt text to images.",
    "Added support for custom URL slugs in routing.",
    "Refactored UI components to use Emotion CSS library.",
    "Updated README with performance benchmarks.",
    "Fixed bugs causing duplicate notifications.",
    "Improved error handling in file processing pipelines.",
    "Added support for webhook event subscriptions.",
    "Refined form layout for better readability.",
    "Updated dependencies to fix compatibility issues.",
    "Fixed bugs causing incorrect form validation results.",
    "Improved accessibility by using semantic HTML5 elements.",
    "Added feature to customize user onboarding flows.",
    "Refactored authentication context for centralized state.",
    "Updated localization files with gender-neutral terms.",
    "Fixed bugs causing crashes on Android devices.",
    "Improved test coverage with automated UI testing.",
    "Added support for exporting analytics reports.",
    "Refined CSS variables to enable dynamic theming.",
    "Updated build scripts to integrate automated testing.",
    "Fixed bugs in drag-and-drop sorting functionality.",
    "Improved accessibility by ensuring logical tab order.",
    "Added feature to support custom user notifications.",
    "Refactored 'useDataFetcher' hook to improve data caching.",
    "Updated documentation to include API usage tutorials.",
    "Fixed bugs related to session timeout handling.",
    "Improved error messages for file upload failures.",
    "Added support for OAuth login with multiple providers.",
    "Refined UI to enhance mobile touch interactions.",
    "Updated localization files for seasonal campaigns.",
    "Fixed bugs causing layout issues in legacy browsers.",
    "Improved accessibility of dropdown select elements.",
    "Added support for real-time user presence indicators.",
    "Refactored form validation to use Yup schema.",
    "Updated README with tips for optimizing bundle size.",
    "Fixed bugs in keyboard shortcut handling.",
    "Improved error feedback for invalid form inputs.",
    "Added support for exporting user activity logs in CSV.",
    "Refined API client error handling strategies.",
    "Updated dependencies to support Node.js 18.",
    "Fixed bugs related to user role changes.",
    "Improved accessibility of nested menus.",
    "Added feature to support dark theme switching.",
    "Refactored UI components to improve testability.",
    "Updated localization files to include slang and colloquialisms.",
    "Fixed bugs causing inconsistent font rendering.",
    "Improved error logging during server-side rendering.",
    "Added support for password strength validation.",
    "Refined caching mechanisms in data fetching hooks.",
    "Updated build scripts to support multi-target builds.",
    "Fixed bugs with missing ARIA attributes.",
    "Improved accessibility of progress bars.",
    "Added support for exporting data in YAML format.",
    "Refactored 'UserProfile.jsx' to use context API more efficiently.",
    "Updated dependencies to remove deprecated methods.",
    "Fixed bugs causing errors in form autofill.",
    "Improved test suite by adding mocking utilities.",
    "Added feature to send welcome emails upon registration.",
    "Refined CSS styles for consistent button appearance.",
    "Updated README with security best practices.",
    "Fixed bugs with focus management in modal dialogs.",
    "Improved accessibility by adding landmarks for navigation.",
    "Added support for exporting dashboard data in JSON format.",
    "Refactored form components to integrate with Formik.",
    "Updated localization files for new terminology.",
    "Fixed bugs causing layout breaks on high-DPI displays.",
    "Improved error handling in WebSocket connections.",
    "Added support for progressive web app (PWA) features.",
    "Refined API authentication flow for better user security.",
    "Updated build tools to enable faster incremental rebuilds.",
    "Fixed bugs causing flickering UI elements.",
    "Improved accessibility by ensuring all form controls have labels.",
    "Added support for customizing error messages globally.",
    "Refactored Redux store to use RTK Query for data fetching.",
    "Updated README with instructions for local development.",
    "Fixed bugs related to date/time picker components.",
    "Improved error handling in background sync processes.",
    "Added feature to schedule notifications based on user activity.",
    "Refined UI components to support high contrast mode.",
    "Updated localization files to include regional dialects.",
    "Fixed bugs causing data inconsistency in cache.",
    "Improved test coverage by adding unit tests for hooks.",
    "Added support for exporting analytics dashboards as PDFs.",
    "Refactored authentication provider to improve token refresh handling.",
    "Updated dependencies to support latest React version.",
    "Fixed bugs related to form input focus loss.",
    "Improved accessibility by enhancing screen reader announcements.",
    "Added feature to allow users to download invoices.",
    "Refined CSS styles for better support of right-to-left languages.",
    "Updated build scripts to integrate code coverage reports.",
    "Fixed bugs causing errors in multi-language support.",
    "Improved error messages for network request failures.",
    "Added support for user profile customization options.",
    "Refactored API service layer for better separation of concerns.",
    "Updated documentation to include API rate limiting info.",
    "Fixed bugs related to offline form validation.",
    "Improved accessibility by providing better focus outlines.",
    "Added feature flag support for gradual feature rollout.",
    "Refined UI components for better error state display.",
    "Updated localization files to improve translation consistency.",
    "Fixed bugs causing layout breaks on landscape orientation.",
    "Improved error handling for file upload cancellations.",
    "Added support for exporting user preferences.",
    "Refactored codebase to follow SOLID principles.",
    "Updated dependencies to improve build times.",
    "Fixed bugs with inconsistent tooltip behavior.",
    "Improved accessibility of data tables with sortable columns.",
    "Added feature to track user session durations.",
    "Refined CSS for better theming capabilities.",
    "Updated README with detailed API endpoint documentation.",
    "Fixed bugs causing crashes on certain Android versions.",
    "Improved error reporting in server logs.",
    "Added support for international phone number validation.",
    "Refactored form components to support dynamic fields.",
    "Updated build configuration to enable source map support.",
    "Fixed bugs causing incorrect error message display.",
    "Improved accessibility by supporting screen magnifiers.",
    "Added support for exporting data to third-party CRM systems.",
    "Refined API error messages for better developer experience.",
    "Updated localization files with seasonal updates.",
    "Fixed bugs in list filtering logic.",
    "Improved user feedback with animated loading indicators.",
    "Added support for server-side rendering optimizations.",
    "Refactored state management to improve performance.",
    "Updated README with troubleshooting for common errors.",
    "Fixed bugs related to session cookie handling.",
    "Improved accessibility of modal window close buttons.",
    "Added feature to support user activity logs export.",
    "Refined CSS styles for better support on retina displays.",
    "Updated dependencies to latest security patches.",
    "Fixed bugs causing issues in multi-step wizards.",
    "Improved error handling for third-party API rate limits.",
    "Added support for exporting user-generated reports.",
    "Refactored codebase to modularize utility functions.",
    "Updated README to include API deprecation timelines.",
    "Fixed bugs causing layout shifts during page transitions.",
    "Improved accessibility by providing alternative text for icons.",
    "Added feature to allow users to opt-in for beta programs.",
    "Refined form validation error display for mobile devices.",
    "Updated localization files to add new language support.",
    "Fixed bugs causing errors in push notification delivery.",
    "Improved error handling in background job retries.",
    "Added support for serverless function deployments.",
    "Refactored authentication context for improved token management.",
    "Updated build tools to support ES2022 syntax.",
    "Fixed bugs with SVG rendering issues.",
    "Improved accessibility of form controls with ARIA labels.",
    "Added feature to schedule automated database backups.",
    "Refined UI components to improve keyboard accessibility.",
    "Updated README with deployment checklist.",
    "Fixed bugs in API authentication token refresh.",
    "Improved error messages for file format validation.",
    "Added support for bulk importing user data.",
    "Refactored code to support modular CSS architectures.",
    "Updated localization files with accessibility improvements.",
    "Fixed bugs related to slow rendering on low-end devices.",
    "Improved user experience with improved form focus management.",
    "Added support for exporting audit logs.",
    "Refined caching layers to improve offline data access.",
    "Updated build process to integrate Webpack Bundle Analyzer.",
    "Fixed bugs with inconsistent form submission handling.",
    "Improved accessibility by supporting high contrast themes.",
    "Added feature to allow admins to impersonate users.",
    "Refactored Redux logic to simplify async actions.",
    "Updated documentation to include API best practices.",
    "Fixed bugs causing layout breaks on large screens.",
    "Improved error feedback on form validation failures.",
    "Added support for multi-tenant deployments.",
    "Refined CSS styles to improve hover effects.",
    "Updated localization files to improve text clarity.",
    "Fixed bugs related to client-side caching inconsistencies.",
    "Improved accessibility of navigation menus with ARIA attributes.",
    "Added feature to support user data anonymization.",
    "Refactored API error handling to provide more detailed responses.",
    "Updated README with security audit checklist.",
    "Fixed bugs causing data duplication in database.",
    "Improved performance of image lazy loading.",
    "Added support for importing data from external CSV files.",
    "Refined UI components to enhance focus states.",
    "Updated build configuration to support incremental compilation.",
    "Fixed bugs causing unexpected behavior in drag-and-drop interfaces.",
    "Improved accessibility by adding descriptive page titles.",
    "Added support for exporting data visualizations.",
    "Refactored form components to improve accessibility compliance.",
    "Updated localization files with feedback from users.",
    "Fixed bugs causing layout breaks on different screen orientations.",
    "Improved error handling in asynchronous operations.",
    "Added feature to allow users to customize notification sounds.",
    "Refined caching strategies to reduce redundant network requests.",
    "Updated dependencies to address licensing issues.",
    "Fixed bugs related to password reset email delivery.",
    "Improved accessibility by adding focus management in dialogs.",
    "Added support for export of user analytics data.",
    "Refactored Redux store to support entity adapters.",
    "Updated README with best practices for component testing.",
    "Fixed bugs with inconsistent scroll behavior.",
    "Improved error handling in multipart file uploads.",
    "Added feature to log user interactions for analytics.",
    "Refined CSS styles to improve print layout.",
    "Updated build tools to support modern JavaScript features.",
    "Fixed bugs causing crashes on certain device models.",
    "Improved accessibility by labeling",]


const ALLOWED_CODE_EXTENSIONS = ['.html', '.css', '.scss', '.js'];

function getAllFiles(dirPath, arrayOfFiles = []) {
    const files = fs.readdirSync(dirPath);

    files.forEach(file => {
        const fullPath = path.join(dirPath, file);
        if (fs.statSync(fullPath).isDirectory()) {
            getAllFiles(fullPath, arrayOfFiles);
        } else {
            const ext = path.extname(fullPath).toLowerCase();
            if (ALLOWED_CODE_EXTENSIONS.includes(ext)) {
                arrayOfFiles.push(fullPath);
            }
        }
    });

    return arrayOfFiles;
}

// Losowanie elementu z tablicy
function getRandomElement(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function updateLastModifiedDateInFile(filePath) {
    try {
        let content = fs.readFileSync(filePath, 'utf8');
        const today = new Date().toISOString().slice(0, 10);

        if (!content.match(/^\/\/ Last updated:.*$/m)) {
            content = `// Last updated: ${today}\n` + content;
            console.log(`ℹ️ Dodano linię "Last updated" w pliku: ${filePath}`);
        } else {
            content = content.replace(/^\/\/ Last updated:.*$/m, `// Last updated: ${today}`);
            console.log(`ℹ️ Zaktualizowano datę w pliku: ${filePath}`);
        }

        fs.writeFileSync(filePath, content, 'utf8');
    } catch (err) {
        console.error(`❌ Błąd podczas zapisu pliku: ${filePath}`);
        console.error(err);
    }
}

async function commitAndPush(filePath, commitMessage) {
    const git = simpleGit(PROJECT_DIR);

    try {
        await git.add(filePath);
        await git.commit(commitMessage);
        await git.pull(['--rebase']);   // najpierw pobierz i rebase
        await git.push();
        console.log('✅ Commit i push zakończony. Wiadomość:', commitMessage);
    } catch (err) {
        console.error('❌ Błąd podczas commitowania lub pushowania:', err);
    }
}

async function run() {
    if (!fs.existsSync(PROJECT_DIR)) {
        console.error('❌ Katalog projektu nie istnieje:', PROJECT_DIR);
        return;
    }

    const allFiles = getAllFiles(PROJECT_DIR);

    if (allFiles.length === 0) {
        console.error('❌ Nie znaleziono żadnych plików w katalogu projektu.');
        return;
    }

    for (let i = 0; i < 10; i++) {
        const randomFile = getRandomElement(allFiles);
        console.log(`📄 Wybrano plik: ${randomFile}`); // <-- TU

        updateLastModifiedDateInFile(randomFile);

        const commitMessage = getRandomElement(COMMIT_MESSAGES);

        const relativeFilePath = path.relative(PROJECT_DIR, randomFile).replace(/\\/g, '/');

        await commitAndPush(relativeFilePath, commitMessage);

        if (i < 9) {
            console.log('⏳ Czekam 2 minuty do następnego commita...');
            await new Promise(res => setTimeout(res, 2 * 60 * 1000)); // 2 minuty
        }
    }
}

run();